---
title: "CV de Yanina Bellini Saibene"
author: Yanina Bellini Saibene
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("CV_printing_functions.R")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Para ver este CV on-line ir a _https://yabellini.netlify.app/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> DEscargar un PDF de este CV]()")
}
```

Contacto {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Hecho con el paquete de R [**pagedown**](https://github.com/rstudio/pagedown). 

El código fuente está disponible en [github.com/nstrayer/cv](https://github.com/yabellini/CV).

Última actualización `r Sys.Date()`.



Main
================================================================================

Yanina Bellini Saibene {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Educación {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Experiencia en Investigación {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Experiencia Docente Seleccionada {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```



Charlas seleccionadas {data-icon=chart-line}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('data_science_writing_aside')
```
:::

```{r}
CV %<>% print_section('data_science_writings')
```



Notas de prensa seleccionadas(sobre mi)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('about_me_press')
```


<br>
<br>


Notas de prensa seleccionadas(escritas por mi)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('by_me_press')
```



Libros y otras publicaciones seleccionadas {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```
